### ISSUE TITLE
T0 tasks broken

### ISSUE THREAD

**Issue by gahdritz** [google-research/FLAN#21]
This has already been mentioned in #17, but I think it's worth surfacing as a separate issue.

TFDS (even the most recent `tfds-nightly`) does not recognize the names provided for the T0 datasets in `flan/v2/task_configs.py`. e.g. `tfds build huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q` crashes.

**Comment by alexchapeaux** [comment]
When I try to generate T0 (few-shot) I get `KeyError: "Trying to access splits['train'] but splits is empty. This likely indicate the dataset has not been generated yet.`

**Comment by gauravmishra** [comment]
I posted an update on #17 but re-posting here as well since it's actually more relevant to the problem reported here:

I've reported the error to the TFDS folks and will post an update as soon as I hear back. It looks like the underlying TFDS dataset is broken, e.g. running the following on Colab:

!pip install datasets
!pip install tensorflow_datasets
import tensorflow_datasets as tfds
ds = tfds.load("huggingface:bigscience__p3/adversarial_qa_dbert_answer_the_following_q", split="train")

Gives me this error:
ValueError: 'full' is not a valid VerificationMode

**Comment by shayne-longpre** [comment]
Looks like this may have been fixed, following #17. Closing if so. Feel free to open a new Issue if not.

**Comment by lehougoogle** [comment]
Closing this issue for now. Plz re-open if needed.
