### ISSUE TITLE
Mixture used to train FLAN-T5 / UL2

### ISSUE THREAD

**Issue by ma2rten** [google-research/FLAN#27]
It would be great if you could add the exact mixture used to train FLAN-T5 and FLAN-UL2. This is not trivial because it doesn't look like limiting the number of examples per task is implemented in this repo.

**Comment by shayne-longpre** [comment]
@ma2rten Thanks for the question -- I will update the README with more details on this very soon. The per task example maximums should be passed in here (https://github.com/google-research/FLAN/blob/main/flan/v2/mixtures.py#L84). Quite a few things had to change from internally to release this code, so it's possible there is a bug we haven't caught -- please let us know if you're seeing one! We've found one issue with the Natural Instructions split we will push a fix for very soon.

@ioana-blue The full list of datasets used in training, with some of their metadata, is available in this file: https://github.com/google-research/FLAN/blob/main/flan/v2/flan_collection_info.csv.

**Comment by ioana-blue** [comment]
@shayne-longpre Thanks for the prompt reply, much appreciated.

**Comment by shayne-longpre** [comment]
@ma2rten I plan to merge this soon after review, but take a look at the new `flan/v2/run_example.py` file. It has the recommended mixture rates: https://github.com/google-research/FLAN/pull/34

If you're seeing an issue with mixture rates / example capping not being applied as you expected, I'm told it might be because of this: https://github.com/google/seqio/pull/490. When this is in, the `flan/v2/run_example.py` script should keep generating examples according to the correct rates, until the first dataset runs out of examples (1 epoch).

**Comment by shayne-longpre** [comment]
> 

Merged. And the seqio fix is in as well. Let me know if you hit any issues!

**Comment by ma2rten** [comment]
Awesome!

I will give it a try this week.
