### ISSUE TITLE
base model for self-query?

### ISSUE THREAD

**Issue by i-am-neo** [google-research/FLAN#39]
Thanks to the FLAN team for open-sourcing your methods and prompts!

If I want to create a system that can self-query - generate its own options and decide on a best option depending on context, which pre-trained model would you recommend as a baseline model?  
Would any of the Flan-T5 models (or U2) currently published on Huggingface be sufficient?  Would you recommend further finetuning?

Thank you.

**Comment by shayne-longpre** [comment]
@i-am-neo Thank you for your question!

I would suggest you use the largest size model in the Flan-T5/UL2 series that fits your hardware/latency/cost requirements. And yep, they are all on Huggingface. 

The task of generating your own answer options from the instruction is an interesting one. I would probably suggest further finetuning since this is not a common setup. You could generate your own finetuning data from the Flan Collection, across many tasks, by manipulating the `zsopt` (Zero Shot prompted with Answer Options) submixtures. Simply remove the answer options in their final generated input, and prepend those to the gold output text.

**Comment by i-am-neo** [comment]
Thanks for your suggestion. Another perhaps related one - have you experimented with prompts that encourage say Flan-T5xl to "express" responses in a certain style?  For example, "in bullet points" or "in prose" or "in fully formed sentences" or "one cohesive paragraph."

Could you share some suggestions?

**Comment by shayne-longpre** [comment]
@i-am-neo I have not experimented with this. Only a subset of the Flan Collection data asks for responses like this, due to the nature of most academic training tasks. If this is your goal you may wish to do additional finetuning on more prose-like open-ended generation, or use the Flan Collection with a bigger model (Flan-UL2 or larger), where the models seem more capable of these tasks.
